title: Jay Havaldar
description: Math PhD Student | Programmer | Music Fan
show_downloads: true
google_analytics:
theme:
markdown: kramdown
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

