title: Jay Havaldar
description: Math Student, Programmer, Music Fan
url: https://jhavaldar.github.io
author: Jay Havaldar
twitter:
  username: JayHavaldar
show_downloads: true
google_analytics: true
markdown: kramdown
twitter_username:     JayHavaldar
github_username:      jhavaldar
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
gems: [jekyll-seo-tag]

